// export const URL_API = 'http://ec2-3-141-36-22.us-east-2.compute.amazonaws.com:9090'
export const URL_API = 'http://localhost:9090'
export const URL_PACIENTES = URL_API + '/pacientes'
export const URI_ANTECEDENTES_MEDICOS = 'antecedentes-medicos'
export const URI_DIAGNOSTICOS = 'diagnosticos'
export const URI_APOYOS_DOMICILIARIOS = 'apoyos-domiciliarios'
export const URI_LESIONES = 'lesiones'
export const URI_SESIONES = 'sesiones'
export const URI_RUTINAS = 'rutinas'

export const URL_MARCAS = URL_API + '/marcas'
